In [ ]:
a=1.1
print(a)

1.1

In [ ]:
list1=range(1, 10)
print(list(list1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
lst=[5,1,5,12,4,423,423,423,423,4,23]
print("Array elements:", lst)
lst[0:6:1]


list(range(1,5,2))

Array elements: [5, 1, 5, 12, 4, 423, 423, 423, 423, 4, 23]

[1, 3]

In [ ]:
# 2*1 = 2

for i in range(0, 11):
    print(f"2 * {i} = {2*i}")
    if i==11:
        print("End of table")

print("Continuing...")

2 * 0 = 0
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
Continuing...

In [ ]:
# *
# **
# ***

for i in range(1, 4):
    print('*' * i)
# ***
# **
# *
for i in range(10, 0,-2):
    print('*' * i)

*
**
***
**********
********
******
****
**

In [ ]:
# *****
#  ***
#   *
for i in range(5, 0, -2):
    print(' ' * ((5 - i)//2) + '*' * i)

*****
 ***
  *

*Star Pattern printing cross odd length numbers*

In [ ]:
nums = "1234567"

for i in range(len(nums)):
    for j in range(len(nums)):
        if i == j or i + j == len(nums)-1:
            print(nums[i], end = " ")
        else:
            print(" ", end = " ")
    print()

1           1
  2       2
    3   3
      4
    5   5
  6       6
7           7

*Star Pattern printing cross odd length numbers*

In [ ]:
nums = "7654321"

for i in range(len(nums)):
    for j in range(len(nums)):
        if i == j or i + j == len(nums)-1:
            print(nums[j], end = " ")
        else:
            print(" ", end = " ")
    print()

7           1
  6       2
    5   3
      4
    5   3
  6       2
7           1

*Pattern printing numbers*

In [ ]:
nums = 4

for i in range(nums):
    k = 111
    for j in range(i+1):
        print(k, end =" ")
        k += 111
    print()

111
111 222
111 222 333
111 222 333 444

*Pattern printing numbers*

In [ ]:
nums = 5

for i in range(nums):
    k = 111
    for j in range(nums-i-1):
        print("   ", end = " ")
    for j in range(i+1):
        print(k, end =" ")
        k += 111
    print()

                111
            111 222
        111 222 333
    111 222 333 444
111 222 333 444 555

*Pattern printing numbers*

In [ ]:
nums = 5

for i in range(nums):
    k = 111
    for j in range(nums-i-1):
        print("   ", end = " ")
    k *= (i+1)
    for j in range(i+1):
        print(k, end =" ")
        k -= 111
    print()

                111
            222 111
        333 222 111
    444 333 222 111
555 444 333 222 111

Diamond Star Pattern

In [ ]:
row = 5
for i in range(row):
    for j in range(row-i):
        print(format("*", "<2"), end = "")
    for j in range(row - (row-i)):
        print(format("","<1"), end = "")
    # print()
    for j in range(row - (row-i)):
        print(format(" ", ">3"), end = "")
    for j in range(row-i):
        print(format("*", ">2"), end = "")
    print()

for i in range(row):
    for j in range(i+1):
        print(format("*", "<2"), end = "")
    for j in range(row-1-i):
        print(format("", "<1"), end = "")
    for j in range(row-1-i):
        print(format(" ", ">3"), end = "")
    for j in range(i+1):
        print(format("*", ">2"), end = "")

    print()

* * * * *  * * * * *
* * * *      * * * *
* * *          * * *
* *              * *
*                  *
*                  *
* *              * *
* * *          * * *
* * * *      * * * *
* * * * *  * * * * *

LCM

In [ ]:
class Solution:
    # @staticmethod
    def Compute_LCM(self,n1, n2):
        if n1 > n2:
            higher = n1
        else:
            higher = n2

        value = higher

        while True:
            if higher % n1 == 0 and higher % n2 == 0:
                return(f"LCM of {n1} and {n2} is {higher}")
                break
            else:
                higher += value
sol = Solution()
print(sol.Compute_LCM(108,901))

LCM of 108 and 901 is 97308

Diamond Numbers Pattern

In [ ]:
# Q: Number Diamond Pattern

num = 9
# For space we can do this as well but this will not work for any number of row so have to neglect this approach
# space = (num*2)+1-(row*3) when num = 4

for row in range(num):
    for col in range(num-1-row):
        print(" ", end = "  ")
    for col in range(row+1,0,-1):
        print(col, end = " ")
    if row > 0:
        for col in range(row-1):
            print(" ", end = " ")
        for col in range(row+1):
            print(col+1, end = " ")               
    print()

for row in range(num-1):
    for col in range(row+1):
        print(" ", end = "  ")
    for col in range(num-1-row,0,-1):
        print(col, end = " ")
    if row < (num-2):
        for col in range(num-row-3):
            print(" ", end = " ")
        for col in range(num-row-1):
            print(col+1, end = " ")               
    print()

                        1
                     2 1 1 2
                  3 2 1   1 2 3
               4 3 2 1     1 2 3 4
            5 4 3 2 1       1 2 3 4 5
         6 5 4 3 2 1         1 2 3 4 5 6
      7 6 5 4 3 2 1           1 2 3 4 5 6 7
   8 7 6 5 4 3 2 1             1 2 3 4 5 6 7 8
9 8 7 6 5 4 3 2 1               1 2 3 4 5 6 7 8 9
   8 7 6 5 4 3 2 1             1 2 3 4 5 6 7 8
      7 6 5 4 3 2 1           1 2 3 4 5 6 7
         6 5 4 3 2 1         1 2 3 4 5 6
            5 4 3 2 1       1 2 3 4 5
               4 3 2 1     1 2 3 4
                  3 2 1   1 2 3
                     2 1 1 2
                        1

In [ ]:
2**7 *4

512

In [ ]:
!pip install openpyxl --quiet

56319.65s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

In [ ]:
import pandas as pd
import seaborn as sns
import ydata_profiling as yd
from skimpy import skim 
tit = sns.load_dataset("titanic")
tit.to_excel("./DataSets/tit.xlsx")
tit.to_csv("./DataSets/tit.csv")

In [ ]:
# df = pd.read_csv("./DataSets/tit.csv")
# df_2 = pd.read_excel("./DataSets/tit.xlsx")
df = tit
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [ ]:
profile = yd.ProfileReport(df)
profile.to_file(output_file='./Outputs/ydata_titanic.html')

100%|██████████| 15/15 [00:00<00:00, 1042.60it/s]00:00, 43.68it/s, Describe variable: alone]
Summarize dataset: 100%|██████████| 41/41 [00:03<00:00, 10.38it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:03<00:00,  3.16s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.70it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 206.14it/s]

In [ ]:
df_1 = pd.read_csv('./DataSets/sdp.csv')
profile = yd.ProfileReport(df_1)
profile.to_file(output_file='./Outputs/ydata_pakpop.html')

100%|██████████| 21/21 [00:00<00:00, 1078.78it/s]00:00, 45.90it/s, Describe variable: ANNUAL GROWTH RATE (URBAN)]
Summarize dataset: 100%|██████████| 319/319 [00:40<00:00,  7.87it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.59s/it]
Render HTML: 100%|██████████| 1/1 [00:01<00:00,  1.39s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 37.02it/s]

In [ ]:
skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types               Categories                                        │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓ ┏━━━━━━━━━━━━━━━━━━━━━━━┓                                │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃ ┃ Categorical Variables ┃                                │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩ ┡━━━━━━━━━━━━━━━━━━━━━━━┩                                │
│ │ Number of rows    │ 891    │ │ string      │ 5     │ │ class                 │                                │
│ │ Number of columns │ 15     │ │ int64       │ 4     │ │ deck                  │                                │
│ └───────────────────┴────────┘ │ float64     │ 2     │ └───────────────────────┘                                │
│                                │ category    │ 2     │                                                          │
│                                │ bool        │ 2     │                                                          │
│                                └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column    ┃ NA   ┃ NA %                 ┃ mean    ┃ sd      ┃ p0    ┃ p25   ┃ p50   ┃ p75 ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │ survived  │    0 │                    0 │  0.3838 │  0.4866 │     0 │     0 │     0 │   1 │     1 │ █    ▅ │  │
│ │ pclass    │    0 │                    0 │   2.309 │  0.8361 │     1 │     2 │     3 │   3 │     3 │ ▄  ▃ █ │  │
│ │ age       │  177 │   19.865319865319865 │    29.7 │   14.53 │  0.42 │ 20.12 │    28 │  38 │    80 │ ▂██▃▁  │  │
│ │ sibsp     │    0 │                    0 │   0.523 │   1.103 │     0 │     0 │     0 │   1 │     8 │   █    │  │
│ │ parch     │    0 │                    0 │  0.3816 │  0.8061 │     0 │     0 │     0 │   0 │     6 │  █▁▁   │  │
│ │ fare      │    0 │                    0 │    32.2 │   49.69 │     0 │  7.91 │ 14.45 │  31 │ 512.3 │   █    │  │
│ └───────────┴──────┴──────────────────────┴─────────┴─────────┴───────┴───────┴───────┴─────┴───────┴────────┘  │
│                                                    category                                                     │
│ ┏━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓  │
│ ┃ column          ┃ NA        ┃ NA %                                    ┃ ordered           ┃ unique         ┃  │
│ ┡━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩  │
│ │ class           │         0 │                                       0 │ False             │              3 │  │
│ │ deck            │       688 │                       77.21661054994388 │ False             │              8 │  │
│ └─────────────────┴───────────┴─────────────────────────────────────────┴───────────────────┴────────────────┘  │
│                                                      bool                                                       │
│ ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┓  │
│ ┃ column                            ┃ true            ┃ true rate                     ┃ hist                 ┃  │
│ ┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━┩  │
│ │ adult_male                        │             537 │                           0.6 │        ▅    █        │  │
│ │ alone                             │             537 │                           0.6 │        ▅    █        │  │
│ └───────────────────────────────────┴─────────────────┴───────────────────────────────┴──────────────────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃          ┃           ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min      ┃ max       ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ sex       │  0 │         0 │ male     │ female    │ female   │ male      │      4.7 │         1 │      891 │  │
│ │ embarked  │  2 │ 0.2244668 │ S        │ S         │ C        │ S         │        1 │         1 │      889 │  │
│ │           │    │ 911335578 │          │           │          │           │          │           │          │  │
│ │ who       │  0 │         0 │ man      │ woman     │ child    │ woman     │     3.79 │         1 │      891 │  │
│ │ embark_to │  2 │ 0.2244668 │ Cherbour │ Southampt │ Cherbour │ Southampt │     10.5 │         1 │      889 │  │
│ │ wn        │    │ 911335578 │ g        │ on        │ g        │ on        │          │           │          │  │
│ │ alive     │  0 │         0 │ no       │ yes       │ no       │ yes       │     2.38 │         1 │      891 │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

In [ ]:
df_02 = pd.read_csv('./DataSets/Playstore_final.csv')